# Models For Stationary Time Series


In this chapter we will discuss family of autoregressive moving average (ARMA) time series models.

## General Linear Process

A \textbf{linear process} is a time series written as an infinite linear combination of random shocks $\{\varepsilon_t\}$:

$$X_t = \mu + \sum_{j=0}^{\infty} \psi_j \, \varepsilon_{t-j},$$

where:
\begin{itemize}
    \item $\mu$ is the mean,
    \item $\{\psi_j\}$ are coefficients (weights),
    \item $\varepsilon_t \sim \text{i.i.d. } (0, \sigma^2)$ are white noise shocks.
\end{itemize}

## Autoregressive Models

$Y_t = \alpha + \phi_1 Y_{t-1} + \phi_2 Y_{t-2} + \dots + \phi_p Y_{t-p} + \epsilon_t$

Where:

$Y_t$ is the value at time $t$

$\alpha$ is a constant,

$\phi_1, \phi_2,...\phi_p$ are the parameters,

$\epsilon_t$ is white noise (error term),

$p$ is the order of the AR model.

## In-class: Properties of AR(1) process

Derive

-   Mean

-   Variance

-   Covariance

-   Autocorrelation function of an AR(1) process

## In-class: Properties of AR(2) process

Derive

-   Mean

-   Variance

-   Covariance

-   Autocorrelation function of an AR(1) process


## In-class: Properties of AR(P) process

Derive

-   Mean

-   Variance

-   Covariance

-   Autocorrelation function of an AR(P) process
